package com.cnwisdom.Prometheus.dao.cloudros.mapper;

import com.cnwisdom.Prometheus.dao.cloudros.entity.TWarnConfig;
import com.cnwisdom.Prometheus.dao.cloudros.entity.TWarnConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TWarnConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_warn_config
     *
     * @mbg.generated Mon Oct 16 11:58:54 CST 2017
     */
    long countByExample(TWarnConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_warn_config
     *
     * @mbg.generated Mon Oct 16 11:58:54 CST 2017
     */
    int deleteByExample(TWarnConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_warn_config
     *
     * @mbg.generated Mon Oct 16 11:58:54 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_warn_config
     *
     * @mbg.generated Mon Oct 16 11:58:54 CST 2017
     */
    int insert(TWarnConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_warn_config
     *
     * @mbg.generated Mon Oct 16 11:58:54 CST 2017
     */
    int insertSelective(TWarnConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_warn_config
     *
     * @mbg.generated Mon Oct 16 11:58:54 CST 2017
     */
    List<TWarnConfig> selectByExample(TWarnConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_warn_config
     *
     * @mbg.generated Mon Oct 16 11:58:54 CST 2017
     */
    TWarnConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_warn_config
     *
     * @mbg.generated Mon Oct 16 11:58:54 CST 2017
     */
    int updateByExampleSelective(@Param("record") TWarnConfig record, @Param("example") TWarnConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_warn_config
     *
     * @mbg.generated Mon Oct 16 11:58:54 CST 2017
     */
    int updateByExample(@Param("record") TWarnConfig record, @Param("example") TWarnConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_warn_config
     *
     * @mbg.generated Mon Oct 16 11:58:54 CST 2017
     */
    int updateByPrimaryKeySelective(TWarnConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_warn_config
     *
     * @mbg.generated Mon Oct 16 11:58:54 CST 2017
     */
    int updateByPrimaryKey(TWarnConfig record);
}