package com.cnwisdom.Prometheus.dao.cloudros.entity;

import java.util.Date;

public class TWarnConfig {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_warn_config.id
     *
     * @mbg.generated Mon Oct 16 11:58:54 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_warn_config.warntype
     *
     * @mbg.generated Mon Oct 16 11:58:54 CST 2017
     */
    private String warntype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_warn_config.warnname
     *
     * @mbg.generated Mon Oct 16 11:58:54 CST 2017
     */
    private String warnname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_warn_config.warnvalue
     *
     * @mbg.generated Mon Oct 16 11:58:54 CST 2017
     */
    private String warnvalue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_warn_config.warnlevel
     *
     * @mbg.generated Mon Oct 16 11:58:54 CST 2017
     */
    private Integer warnlevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_warn_config.inuse
     *
     * @mbg.generated Mon Oct 16 11:58:54 CST 2017
     */
    private Integer inuse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_warn_config.createtime
     *
     * @mbg.generated Mon Oct 16 11:58:54 CST 2017
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_warn_config.lastupdatetime
     *
     * @mbg.generated Mon Oct 16 11:58:54 CST 2017
     */
    private Date lastupdatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_warn_config.comm1
     *
     * @mbg.generated Mon Oct 16 11:58:54 CST 2017
     */
    private String comm1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_warn_config.comm2
     *
     * @mbg.generated Mon Oct 16 11:58:54 CST 2017
     */
    private String comm2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_warn_config.closetype
     *
     * @mbg.generated Mon Oct 16 11:58:54 CST 2017
     */
    private Integer closetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_warn_config.inform
     *
     * @mbg.generated Mon Oct 16 11:58:54 CST 2017
     */
    private Integer inform;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_warn_config.orderstate
     *
     * @mbg.generated Mon Oct 16 11:58:54 CST 2017
     */
    private Integer orderstate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_warn_config.id
     *
     * @return the value of t_warn_config.id
     *
     * @mbg.generated Mon Oct 16 11:58:54 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_warn_config.id
     *
     * @param id the value for t_warn_config.id
     *
     * @mbg.generated Mon Oct 16 11:58:54 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_warn_config.warntype
     *
     * @return the value of t_warn_config.warntype
     *
     * @mbg.generated Mon Oct 16 11:58:54 CST 2017
     */
    public String getWarntype() {
        return warntype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_warn_config.warntype
     *
     * @param warntype the value for t_warn_config.warntype
     *
     * @mbg.generated Mon Oct 16 11:58:54 CST 2017
     */
    public void setWarntype(String warntype) {
        this.warntype = warntype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_warn_config.warnname
     *
     * @return the value of t_warn_config.warnname
     *
     * @mbg.generated Mon Oct 16 11:58:54 CST 2017
     */
    public String getWarnname() {
        return warnname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_warn_config.warnname
     *
     * @param warnname the value for t_warn_config.warnname
     *
     * @mbg.generated Mon Oct 16 11:58:54 CST 2017
     */
    public void setWarnname(String warnname) {
        this.warnname = warnname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_warn_config.warnvalue
     *
     * @return the value of t_warn_config.warnvalue
     *
     * @mbg.generated Mon Oct 16 11:58:54 CST 2017
     */
    public String getWarnvalue() {
        return warnvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_warn_config.warnvalue
     *
     * @param warnvalue the value for t_warn_config.warnvalue
     *
     * @mbg.generated Mon Oct 16 11:58:54 CST 2017
     */
    public void setWarnvalue(String warnvalue) {
        this.warnvalue = warnvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_warn_config.warnlevel
     *
     * @return the value of t_warn_config.warnlevel
     *
     * @mbg.generated Mon Oct 16 11:58:54 CST 2017
     */
    public Integer getWarnlevel() {
        return warnlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_warn_config.warnlevel
     *
     * @param warnlevel the value for t_warn_config.warnlevel
     *
     * @mbg.generated Mon Oct 16 11:58:54 CST 2017
     */
    public void setWarnlevel(Integer warnlevel) {
        this.warnlevel = warnlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_warn_config.inuse
     *
     * @return the value of t_warn_config.inuse
     *
     * @mbg.generated Mon Oct 16 11:58:54 CST 2017
     */
    public Integer getInuse() {
        return inuse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_warn_config.inuse
     *
     * @param inuse the value for t_warn_config.inuse
     *
     * @mbg.generated Mon Oct 16 11:58:54 CST 2017
     */
    public void setInuse(Integer inuse) {
        this.inuse = inuse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_warn_config.createtime
     *
     * @return the value of t_warn_config.createtime
     *
     * @mbg.generated Mon Oct 16 11:58:54 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_warn_config.createtime
     *
     * @param createtime the value for t_warn_config.createtime
     *
     * @mbg.generated Mon Oct 16 11:58:54 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_warn_config.lastupdatetime
     *
     * @return the value of t_warn_config.lastupdatetime
     *
     * @mbg.generated Mon Oct 16 11:58:54 CST 2017
     */
    public Date getLastupdatetime() {
        return lastupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_warn_config.lastupdatetime
     *
     * @param lastupdatetime the value for t_warn_config.lastupdatetime
     *
     * @mbg.generated Mon Oct 16 11:58:54 CST 2017
     */
    public void setLastupdatetime(Date lastupdatetime) {
        this.lastupdatetime = lastupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_warn_config.comm1
     *
     * @return the value of t_warn_config.comm1
     *
     * @mbg.generated Mon Oct 16 11:58:54 CST 2017
     */
    public String getComm1() {
        return comm1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_warn_config.comm1
     *
     * @param comm1 the value for t_warn_config.comm1
     *
     * @mbg.generated Mon Oct 16 11:58:54 CST 2017
     */
    public void setComm1(String comm1) {
        this.comm1 = comm1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_warn_config.comm2
     *
     * @return the value of t_warn_config.comm2
     *
     * @mbg.generated Mon Oct 16 11:58:54 CST 2017
     */
    public String getComm2() {
        return comm2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_warn_config.comm2
     *
     * @param comm2 the value for t_warn_config.comm2
     *
     * @mbg.generated Mon Oct 16 11:58:54 CST 2017
     */
    public void setComm2(String comm2) {
        this.comm2 = comm2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_warn_config.closetype
     *
     * @return the value of t_warn_config.closetype
     *
     * @mbg.generated Mon Oct 16 11:58:54 CST 2017
     */
    public Integer getClosetype() {
        return closetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_warn_config.closetype
     *
     * @param closetype the value for t_warn_config.closetype
     *
     * @mbg.generated Mon Oct 16 11:58:54 CST 2017
     */
    public void setClosetype(Integer closetype) {
        this.closetype = closetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_warn_config.inform
     *
     * @return the value of t_warn_config.inform
     *
     * @mbg.generated Mon Oct 16 11:58:54 CST 2017
     */
    public Integer getInform() {
        return inform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_warn_config.inform
     *
     * @param inform the value for t_warn_config.inform
     *
     * @mbg.generated Mon Oct 16 11:58:54 CST 2017
     */
    public void setInform(Integer inform) {
        this.inform = inform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_warn_config.orderstate
     *
     * @return the value of t_warn_config.orderstate
     *
     * @mbg.generated Mon Oct 16 11:58:54 CST 2017
     */
    public Integer getOrderstate() {
        return orderstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_warn_config.orderstate
     *
     * @param orderstate the value for t_warn_config.orderstate
     *
     * @mbg.generated Mon Oct 16 11:58:54 CST 2017
     */
    public void setOrderstate(Integer orderstate) {
        this.orderstate = orderstate;
    }
}