package com.cnwisdom.Prometheus.dao.cloudros.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TWarnConfigExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_warn_config
     *
     * @mbg.generated Mon Oct 16 11:58:54 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_warn_config
     *
     * @mbg.generated Mon Oct 16 11:58:54 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_warn_config
     *
     * @mbg.generated Mon Oct 16 11:58:54 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_warn_config
     *
     * @mbg.generated Mon Oct 16 11:58:54 CST 2017
     */
    public TWarnConfigExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_warn_config
     *
     * @mbg.generated Mon Oct 16 11:58:54 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_warn_config
     *
     * @mbg.generated Mon Oct 16 11:58:54 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_warn_config
     *
     * @mbg.generated Mon Oct 16 11:58:54 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_warn_config
     *
     * @mbg.generated Mon Oct 16 11:58:54 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_warn_config
     *
     * @mbg.generated Mon Oct 16 11:58:54 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_warn_config
     *
     * @mbg.generated Mon Oct 16 11:58:54 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_warn_config
     *
     * @mbg.generated Mon Oct 16 11:58:54 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_warn_config
     *
     * @mbg.generated Mon Oct 16 11:58:54 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_warn_config
     *
     * @mbg.generated Mon Oct 16 11:58:54 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_warn_config
     *
     * @mbg.generated Mon Oct 16 11:58:54 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_warn_config
     *
     * @mbg.generated Mon Oct 16 11:58:54 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andWarntypeIsNull() {
            addCriterion("warntype is null");
            return (Criteria) this;
        }

        public Criteria andWarntypeIsNotNull() {
            addCriterion("warntype is not null");
            return (Criteria) this;
        }

        public Criteria andWarntypeEqualTo(String value) {
            addCriterion("warntype =", value, "warntype");
            return (Criteria) this;
        }

        public Criteria andWarntypeNotEqualTo(String value) {
            addCriterion("warntype <>", value, "warntype");
            return (Criteria) this;
        }

        public Criteria andWarntypeGreaterThan(String value) {
            addCriterion("warntype >", value, "warntype");
            return (Criteria) this;
        }

        public Criteria andWarntypeGreaterThanOrEqualTo(String value) {
            addCriterion("warntype >=", value, "warntype");
            return (Criteria) this;
        }

        public Criteria andWarntypeLessThan(String value) {
            addCriterion("warntype <", value, "warntype");
            return (Criteria) this;
        }

        public Criteria andWarntypeLessThanOrEqualTo(String value) {
            addCriterion("warntype <=", value, "warntype");
            return (Criteria) this;
        }

        public Criteria andWarntypeLike(String value) {
            addCriterion("warntype like", value, "warntype");
            return (Criteria) this;
        }

        public Criteria andWarntypeNotLike(String value) {
            addCriterion("warntype not like", value, "warntype");
            return (Criteria) this;
        }

        public Criteria andWarntypeIn(List<String> values) {
            addCriterion("warntype in", values, "warntype");
            return (Criteria) this;
        }

        public Criteria andWarntypeNotIn(List<String> values) {
            addCriterion("warntype not in", values, "warntype");
            return (Criteria) this;
        }

        public Criteria andWarntypeBetween(String value1, String value2) {
            addCriterion("warntype between", value1, value2, "warntype");
            return (Criteria) this;
        }

        public Criteria andWarntypeNotBetween(String value1, String value2) {
            addCriterion("warntype not between", value1, value2, "warntype");
            return (Criteria) this;
        }

        public Criteria andWarnnameIsNull() {
            addCriterion("warnname is null");
            return (Criteria) this;
        }

        public Criteria andWarnnameIsNotNull() {
            addCriterion("warnname is not null");
            return (Criteria) this;
        }

        public Criteria andWarnnameEqualTo(String value) {
            addCriterion("warnname =", value, "warnname");
            return (Criteria) this;
        }

        public Criteria andWarnnameNotEqualTo(String value) {
            addCriterion("warnname <>", value, "warnname");
            return (Criteria) this;
        }

        public Criteria andWarnnameGreaterThan(String value) {
            addCriterion("warnname >", value, "warnname");
            return (Criteria) this;
        }

        public Criteria andWarnnameGreaterThanOrEqualTo(String value) {
            addCriterion("warnname >=", value, "warnname");
            return (Criteria) this;
        }

        public Criteria andWarnnameLessThan(String value) {
            addCriterion("warnname <", value, "warnname");
            return (Criteria) this;
        }

        public Criteria andWarnnameLessThanOrEqualTo(String value) {
            addCriterion("warnname <=", value, "warnname");
            return (Criteria) this;
        }

        public Criteria andWarnnameLike(String value) {
            addCriterion("warnname like", value, "warnname");
            return (Criteria) this;
        }

        public Criteria andWarnnameNotLike(String value) {
            addCriterion("warnname not like", value, "warnname");
            return (Criteria) this;
        }

        public Criteria andWarnnameIn(List<String> values) {
            addCriterion("warnname in", values, "warnname");
            return (Criteria) this;
        }

        public Criteria andWarnnameNotIn(List<String> values) {
            addCriterion("warnname not in", values, "warnname");
            return (Criteria) this;
        }

        public Criteria andWarnnameBetween(String value1, String value2) {
            addCriterion("warnname between", value1, value2, "warnname");
            return (Criteria) this;
        }

        public Criteria andWarnnameNotBetween(String value1, String value2) {
            addCriterion("warnname not between", value1, value2, "warnname");
            return (Criteria) this;
        }

        public Criteria andWarnvalueIsNull() {
            addCriterion("warnvalue is null");
            return (Criteria) this;
        }

        public Criteria andWarnvalueIsNotNull() {
            addCriterion("warnvalue is not null");
            return (Criteria) this;
        }

        public Criteria andWarnvalueEqualTo(String value) {
            addCriterion("warnvalue =", value, "warnvalue");
            return (Criteria) this;
        }

        public Criteria andWarnvalueNotEqualTo(String value) {
            addCriterion("warnvalue <>", value, "warnvalue");
            return (Criteria) this;
        }

        public Criteria andWarnvalueGreaterThan(String value) {
            addCriterion("warnvalue >", value, "warnvalue");
            return (Criteria) this;
        }

        public Criteria andWarnvalueGreaterThanOrEqualTo(String value) {
            addCriterion("warnvalue >=", value, "warnvalue");
            return (Criteria) this;
        }

        public Criteria andWarnvalueLessThan(String value) {
            addCriterion("warnvalue <", value, "warnvalue");
            return (Criteria) this;
        }

        public Criteria andWarnvalueLessThanOrEqualTo(String value) {
            addCriterion("warnvalue <=", value, "warnvalue");
            return (Criteria) this;
        }

        public Criteria andWarnvalueLike(String value) {
            addCriterion("warnvalue like", value, "warnvalue");
            return (Criteria) this;
        }

        public Criteria andWarnvalueNotLike(String value) {
            addCriterion("warnvalue not like", value, "warnvalue");
            return (Criteria) this;
        }

        public Criteria andWarnvalueIn(List<String> values) {
            addCriterion("warnvalue in", values, "warnvalue");
            return (Criteria) this;
        }

        public Criteria andWarnvalueNotIn(List<String> values) {
            addCriterion("warnvalue not in", values, "warnvalue");
            return (Criteria) this;
        }

        public Criteria andWarnvalueBetween(String value1, String value2) {
            addCriterion("warnvalue between", value1, value2, "warnvalue");
            return (Criteria) this;
        }

        public Criteria andWarnvalueNotBetween(String value1, String value2) {
            addCriterion("warnvalue not between", value1, value2, "warnvalue");
            return (Criteria) this;
        }

        public Criteria andWarnlevelIsNull() {
            addCriterion("warnlevel is null");
            return (Criteria) this;
        }

        public Criteria andWarnlevelIsNotNull() {
            addCriterion("warnlevel is not null");
            return (Criteria) this;
        }

        public Criteria andWarnlevelEqualTo(Integer value) {
            addCriterion("warnlevel =", value, "warnlevel");
            return (Criteria) this;
        }

        public Criteria andWarnlevelNotEqualTo(Integer value) {
            addCriterion("warnlevel <>", value, "warnlevel");
            return (Criteria) this;
        }

        public Criteria andWarnlevelGreaterThan(Integer value) {
            addCriterion("warnlevel >", value, "warnlevel");
            return (Criteria) this;
        }

        public Criteria andWarnlevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("warnlevel >=", value, "warnlevel");
            return (Criteria) this;
        }

        public Criteria andWarnlevelLessThan(Integer value) {
            addCriterion("warnlevel <", value, "warnlevel");
            return (Criteria) this;
        }

        public Criteria andWarnlevelLessThanOrEqualTo(Integer value) {
            addCriterion("warnlevel <=", value, "warnlevel");
            return (Criteria) this;
        }

        public Criteria andWarnlevelIn(List<Integer> values) {
            addCriterion("warnlevel in", values, "warnlevel");
            return (Criteria) this;
        }

        public Criteria andWarnlevelNotIn(List<Integer> values) {
            addCriterion("warnlevel not in", values, "warnlevel");
            return (Criteria) this;
        }

        public Criteria andWarnlevelBetween(Integer value1, Integer value2) {
            addCriterion("warnlevel between", value1, value2, "warnlevel");
            return (Criteria) this;
        }

        public Criteria andWarnlevelNotBetween(Integer value1, Integer value2) {
            addCriterion("warnlevel not between", value1, value2, "warnlevel");
            return (Criteria) this;
        }

        public Criteria andInuseIsNull() {
            addCriterion("inuse is null");
            return (Criteria) this;
        }

        public Criteria andInuseIsNotNull() {
            addCriterion("inuse is not null");
            return (Criteria) this;
        }

        public Criteria andInuseEqualTo(Integer value) {
            addCriterion("inuse =", value, "inuse");
            return (Criteria) this;
        }

        public Criteria andInuseNotEqualTo(Integer value) {
            addCriterion("inuse <>", value, "inuse");
            return (Criteria) this;
        }

        public Criteria andInuseGreaterThan(Integer value) {
            addCriterion("inuse >", value, "inuse");
            return (Criteria) this;
        }

        public Criteria andInuseGreaterThanOrEqualTo(Integer value) {
            addCriterion("inuse >=", value, "inuse");
            return (Criteria) this;
        }

        public Criteria andInuseLessThan(Integer value) {
            addCriterion("inuse <", value, "inuse");
            return (Criteria) this;
        }

        public Criteria andInuseLessThanOrEqualTo(Integer value) {
            addCriterion("inuse <=", value, "inuse");
            return (Criteria) this;
        }

        public Criteria andInuseIn(List<Integer> values) {
            addCriterion("inuse in", values, "inuse");
            return (Criteria) this;
        }

        public Criteria andInuseNotIn(List<Integer> values) {
            addCriterion("inuse not in", values, "inuse");
            return (Criteria) this;
        }

        public Criteria andInuseBetween(Integer value1, Integer value2) {
            addCriterion("inuse between", value1, value2, "inuse");
            return (Criteria) this;
        }

        public Criteria andInuseNotBetween(Integer value1, Integer value2) {
            addCriterion("inuse not between", value1, value2, "inuse");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createtime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createtime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("createtime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("createtime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("createtime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("createtime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("createtime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("createtime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("createtime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("createtime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("createtime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("createtime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andLastupdatetimeIsNull() {
            addCriterion("lastupdatetime is null");
            return (Criteria) this;
        }

        public Criteria andLastupdatetimeIsNotNull() {
            addCriterion("lastupdatetime is not null");
            return (Criteria) this;
        }

        public Criteria andLastupdatetimeEqualTo(Date value) {
            addCriterion("lastupdatetime =", value, "lastupdatetime");
            return (Criteria) this;
        }

        public Criteria andLastupdatetimeNotEqualTo(Date value) {
            addCriterion("lastupdatetime <>", value, "lastupdatetime");
            return (Criteria) this;
        }

        public Criteria andLastupdatetimeGreaterThan(Date value) {
            addCriterion("lastupdatetime >", value, "lastupdatetime");
            return (Criteria) this;
        }

        public Criteria andLastupdatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("lastupdatetime >=", value, "lastupdatetime");
            return (Criteria) this;
        }

        public Criteria andLastupdatetimeLessThan(Date value) {
            addCriterion("lastupdatetime <", value, "lastupdatetime");
            return (Criteria) this;
        }

        public Criteria andLastupdatetimeLessThanOrEqualTo(Date value) {
            addCriterion("lastupdatetime <=", value, "lastupdatetime");
            return (Criteria) this;
        }

        public Criteria andLastupdatetimeIn(List<Date> values) {
            addCriterion("lastupdatetime in", values, "lastupdatetime");
            return (Criteria) this;
        }

        public Criteria andLastupdatetimeNotIn(List<Date> values) {
            addCriterion("lastupdatetime not in", values, "lastupdatetime");
            return (Criteria) this;
        }

        public Criteria andLastupdatetimeBetween(Date value1, Date value2) {
            addCriterion("lastupdatetime between", value1, value2, "lastupdatetime");
            return (Criteria) this;
        }

        public Criteria andLastupdatetimeNotBetween(Date value1, Date value2) {
            addCriterion("lastupdatetime not between", value1, value2, "lastupdatetime");
            return (Criteria) this;
        }

        public Criteria andComm1IsNull() {
            addCriterion("comm1 is null");
            return (Criteria) this;
        }

        public Criteria andComm1IsNotNull() {
            addCriterion("comm1 is not null");
            return (Criteria) this;
        }

        public Criteria andComm1EqualTo(String value) {
            addCriterion("comm1 =", value, "comm1");
            return (Criteria) this;
        }

        public Criteria andComm1NotEqualTo(String value) {
            addCriterion("comm1 <>", value, "comm1");
            return (Criteria) this;
        }

        public Criteria andComm1GreaterThan(String value) {
            addCriterion("comm1 >", value, "comm1");
            return (Criteria) this;
        }

        public Criteria andComm1GreaterThanOrEqualTo(String value) {
            addCriterion("comm1 >=", value, "comm1");
            return (Criteria) this;
        }

        public Criteria andComm1LessThan(String value) {
            addCriterion("comm1 <", value, "comm1");
            return (Criteria) this;
        }

        public Criteria andComm1LessThanOrEqualTo(String value) {
            addCriterion("comm1 <=", value, "comm1");
            return (Criteria) this;
        }

        public Criteria andComm1Like(String value) {
            addCriterion("comm1 like", value, "comm1");
            return (Criteria) this;
        }

        public Criteria andComm1NotLike(String value) {
            addCriterion("comm1 not like", value, "comm1");
            return (Criteria) this;
        }

        public Criteria andComm1In(List<String> values) {
            addCriterion("comm1 in", values, "comm1");
            return (Criteria) this;
        }

        public Criteria andComm1NotIn(List<String> values) {
            addCriterion("comm1 not in", values, "comm1");
            return (Criteria) this;
        }

        public Criteria andComm1Between(String value1, String value2) {
            addCriterion("comm1 between", value1, value2, "comm1");
            return (Criteria) this;
        }

        public Criteria andComm1NotBetween(String value1, String value2) {
            addCriterion("comm1 not between", value1, value2, "comm1");
            return (Criteria) this;
        }

        public Criteria andComm2IsNull() {
            addCriterion("comm2 is null");
            return (Criteria) this;
        }

        public Criteria andComm2IsNotNull() {
            addCriterion("comm2 is not null");
            return (Criteria) this;
        }

        public Criteria andComm2EqualTo(String value) {
            addCriterion("comm2 =", value, "comm2");
            return (Criteria) this;
        }

        public Criteria andComm2NotEqualTo(String value) {
            addCriterion("comm2 <>", value, "comm2");
            return (Criteria) this;
        }

        public Criteria andComm2GreaterThan(String value) {
            addCriterion("comm2 >", value, "comm2");
            return (Criteria) this;
        }

        public Criteria andComm2GreaterThanOrEqualTo(String value) {
            addCriterion("comm2 >=", value, "comm2");
            return (Criteria) this;
        }

        public Criteria andComm2LessThan(String value) {
            addCriterion("comm2 <", value, "comm2");
            return (Criteria) this;
        }

        public Criteria andComm2LessThanOrEqualTo(String value) {
            addCriterion("comm2 <=", value, "comm2");
            return (Criteria) this;
        }

        public Criteria andComm2Like(String value) {
            addCriterion("comm2 like", value, "comm2");
            return (Criteria) this;
        }

        public Criteria andComm2NotLike(String value) {
            addCriterion("comm2 not like", value, "comm2");
            return (Criteria) this;
        }

        public Criteria andComm2In(List<String> values) {
            addCriterion("comm2 in", values, "comm2");
            return (Criteria) this;
        }

        public Criteria andComm2NotIn(List<String> values) {
            addCriterion("comm2 not in", values, "comm2");
            return (Criteria) this;
        }

        public Criteria andComm2Between(String value1, String value2) {
            addCriterion("comm2 between", value1, value2, "comm2");
            return (Criteria) this;
        }

        public Criteria andComm2NotBetween(String value1, String value2) {
            addCriterion("comm2 not between", value1, value2, "comm2");
            return (Criteria) this;
        }

        public Criteria andClosetypeIsNull() {
            addCriterion("closetype is null");
            return (Criteria) this;
        }

        public Criteria andClosetypeIsNotNull() {
            addCriterion("closetype is not null");
            return (Criteria) this;
        }

        public Criteria andClosetypeEqualTo(Integer value) {
            addCriterion("closetype =", value, "closetype");
            return (Criteria) this;
        }

        public Criteria andClosetypeNotEqualTo(Integer value) {
            addCriterion("closetype <>", value, "closetype");
            return (Criteria) this;
        }

        public Criteria andClosetypeGreaterThan(Integer value) {
            addCriterion("closetype >", value, "closetype");
            return (Criteria) this;
        }

        public Criteria andClosetypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("closetype >=", value, "closetype");
            return (Criteria) this;
        }

        public Criteria andClosetypeLessThan(Integer value) {
            addCriterion("closetype <", value, "closetype");
            return (Criteria) this;
        }

        public Criteria andClosetypeLessThanOrEqualTo(Integer value) {
            addCriterion("closetype <=", value, "closetype");
            return (Criteria) this;
        }

        public Criteria andClosetypeIn(List<Integer> values) {
            addCriterion("closetype in", values, "closetype");
            return (Criteria) this;
        }

        public Criteria andClosetypeNotIn(List<Integer> values) {
            addCriterion("closetype not in", values, "closetype");
            return (Criteria) this;
        }

        public Criteria andClosetypeBetween(Integer value1, Integer value2) {
            addCriterion("closetype between", value1, value2, "closetype");
            return (Criteria) this;
        }

        public Criteria andClosetypeNotBetween(Integer value1, Integer value2) {
            addCriterion("closetype not between", value1, value2, "closetype");
            return (Criteria) this;
        }

        public Criteria andInformIsNull() {
            addCriterion("inform is null");
            return (Criteria) this;
        }

        public Criteria andInformIsNotNull() {
            addCriterion("inform is not null");
            return (Criteria) this;
        }

        public Criteria andInformEqualTo(Integer value) {
            addCriterion("inform =", value, "inform");
            return (Criteria) this;
        }

        public Criteria andInformNotEqualTo(Integer value) {
            addCriterion("inform <>", value, "inform");
            return (Criteria) this;
        }

        public Criteria andInformGreaterThan(Integer value) {
            addCriterion("inform >", value, "inform");
            return (Criteria) this;
        }

        public Criteria andInformGreaterThanOrEqualTo(Integer value) {
            addCriterion("inform >=", value, "inform");
            return (Criteria) this;
        }

        public Criteria andInformLessThan(Integer value) {
            addCriterion("inform <", value, "inform");
            return (Criteria) this;
        }

        public Criteria andInformLessThanOrEqualTo(Integer value) {
            addCriterion("inform <=", value, "inform");
            return (Criteria) this;
        }

        public Criteria andInformIn(List<Integer> values) {
            addCriterion("inform in", values, "inform");
            return (Criteria) this;
        }

        public Criteria andInformNotIn(List<Integer> values) {
            addCriterion("inform not in", values, "inform");
            return (Criteria) this;
        }

        public Criteria andInformBetween(Integer value1, Integer value2) {
            addCriterion("inform between", value1, value2, "inform");
            return (Criteria) this;
        }

        public Criteria andInformNotBetween(Integer value1, Integer value2) {
            addCriterion("inform not between", value1, value2, "inform");
            return (Criteria) this;
        }

        public Criteria andOrderstateIsNull() {
            addCriterion("orderstate is null");
            return (Criteria) this;
        }

        public Criteria andOrderstateIsNotNull() {
            addCriterion("orderstate is not null");
            return (Criteria) this;
        }

        public Criteria andOrderstateEqualTo(Integer value) {
            addCriterion("orderstate =", value, "orderstate");
            return (Criteria) this;
        }

        public Criteria andOrderstateNotEqualTo(Integer value) {
            addCriterion("orderstate <>", value, "orderstate");
            return (Criteria) this;
        }

        public Criteria andOrderstateGreaterThan(Integer value) {
            addCriterion("orderstate >", value, "orderstate");
            return (Criteria) this;
        }

        public Criteria andOrderstateGreaterThanOrEqualTo(Integer value) {
            addCriterion("orderstate >=", value, "orderstate");
            return (Criteria) this;
        }

        public Criteria andOrderstateLessThan(Integer value) {
            addCriterion("orderstate <", value, "orderstate");
            return (Criteria) this;
        }

        public Criteria andOrderstateLessThanOrEqualTo(Integer value) {
            addCriterion("orderstate <=", value, "orderstate");
            return (Criteria) this;
        }

        public Criteria andOrderstateIn(List<Integer> values) {
            addCriterion("orderstate in", values, "orderstate");
            return (Criteria) this;
        }

        public Criteria andOrderstateNotIn(List<Integer> values) {
            addCriterion("orderstate not in", values, "orderstate");
            return (Criteria) this;
        }

        public Criteria andOrderstateBetween(Integer value1, Integer value2) {
            addCriterion("orderstate between", value1, value2, "orderstate");
            return (Criteria) this;
        }

        public Criteria andOrderstateNotBetween(Integer value1, Integer value2) {
            addCriterion("orderstate not between", value1, value2, "orderstate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_warn_config
     *
     * @mbg.generated do_not_delete_during_merge Mon Oct 16 11:58:54 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_warn_config
     *
     * @mbg.generated Mon Oct 16 11:58:54 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}